[package]
name = "upload-polarion-attachment"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
percent-encoding = "2.3.1"
reqwest = { version = "0.12.4", features = ["blocking", "json", "multipart"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
